// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvkafitzwkbjoqsrtqzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52a2FmaXR6d2tiam9xc3J0cXppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDQ1MDksImV4cCI6MjA2NTIyMDUwOX0.KHsbuOALpYaN5IeTo6UGE2wi5C4Gh4Ima4Z2kj74fjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);